---
title: "Senate_pfd_scrape.rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
library(janitor)
```
```{r}
####
## Get dataframe of links to loop through
####
# Define html
filings_table_url <- "https://sec.report/Senate-Stock-Disclosures/Filings"

# Read table in
filings_table <- filings_table_url %>%
  read_html() %>%
  html_table() 

# Extraxct from list
filings_table <- filings_table[[1]]

# Create urls to loop through
filings_table <- filings_table %>%
  clean_names() %>%
  filter(title == "Annual Report for CY 2020" & shares_held == "Annual") %>%
  mutate(filed_date = str_sub(filed_date_report_id,start=1L, end=10L)) %>%
  mutate(report_id = str_sub(filed_date_report_id,start=12L, end=-1L)) %>%
  select(filed_date,report_id,everything(),-filed_date_report_id) %>%
  mutate(senator = str_remove_all(reported_by,"[[:punct:]]")) %>%
  separate(senator,into=c("a","b","c","d")) %>%
  mutate(first_name = case_when(
    a == "Ladda" ~ paste0(a,"+",b),
    a == "W" ~ paste0(a,"+",b),
    a == "A" ~ paste0(a,"+",b),
    str_length(b) > 1 ~ a,
    TRUE ~ paste0(a,"+",b)
  )) %>%
  mutate(last_name = case_when(
    a == "Ladda" ~ c,
    a == "W" ~ c,
    c == "III" ~ paste0(b,"+",c),
    is.na(c) ~ b,
    !is.na(d) ~ paste0(c,"+",d),
    str_length(b) == 1 ~ c,
    TRUE ~ d
  )) %>%
  mutate(report_url = paste0(
    "https://sec.report/Senate-Stock-Disclosures/",last_name,"/",first_name,"/",report_id
  )) %>%
  select(-a,-b,-c,-d,-shares_held) %>%
  rename(senator_full_name = reported_by,
         report_title=title,
         senator_first_name = first_name,
         senator_last_name = last_name) %>%
  select(filed_date,report_id, report_title, report_url, senator_full_name,senator_first_name,senator_last_name)

# Create a list of urls to loop through
filings_table_url_list <- filings_table %>%
  select(report_url) %>%
  # for testing
  #slice(1:90) %>%
  as_vector()

# For testing
#report_url_value <- "https://sec.report/Senate-Stock-Disclosures/Toomey/Patrick+J/76ce1651-f934-4bef-91fb-402ef043d1dd"

# All senators table
senators_all <- tibble()

for (report_url_value in filings_table_url_list) {
  
  # Filter senator table for each senator's row
  senator_table <- filings_table %>%
    filter(report_url == report_url_value)
  
  # Grab financial tables
  financial_tables <- report_url_value %>%
    read_html() %>%
    html_table()
 
  # Print length of each list to get number of tables
  number_of_tables <- length(financial_tables)
  
  # create number of tables column
  senator_table <- senator_table %>%
    mutate(number_of_tables = number_of_tables)
  
  # Bind back 
  senators_all <- senators_all %>%
    bind_rows(senator_table)
  #print(number_of_tables)
}

# create empty dataframe to hold results
senator_assets_all <- tibble()
senator_transactions_all <- tibble()
senator_liabilities_all <- tibble()
senator_positions_all <- tibble()
senator_earned_income_all <- tibble()
senator_agreements_all <- tibble()

# for debugging
#report_url_value <- "https://sec.report/Senate-Stock-Disclosures/Sullivan/Daniel+S/7567775a-9f88-42a7-b906-68a4449865a5"
# Loop through and grab all finanical tables 
for (report_url_value in filings_table_url_list) {
  
  # Filter senator table for each senator's row
  senator_table <- filings_table %>%
    filter(report_url == report_url_value)
  
  # print
  print(senator_table$senator_full_name)
  # Grab financial tables
  financial_tables <- report_url_value %>%
    read_html() %>%
    html_table()
 
  ####
  # Grab asset table
  ####
  assets_table <- tibble(
    data = financial_tables
  ) %>%
  filter(str_detect(data,"Asset Type")) %>%
  unnest() %>%
  clean_names() %>%
  mutate(across(everything(), as.character))
  
  # Bind asset table back to senator table
  senator_assets_table <- senator_table %>%
    bind_cols(assets_table)
  
  # Add senator_assets_table to master dataframe
  senator_assets_all <- senator_assets_all %>%
    bind_rows(senator_assets_table)
  
  ####
  # Grab transactions table
  ####
  transactions_table <- tibble(
    data = financial_tables
  ) %>%
  filter(str_detect(data,"Ticker")) %>%
  unnest() %>%
  clean_names() %>%
  mutate(across(everything(), as.character))
  
  # Bind asset table back to senator table
  senator_transactions_table <- senator_table %>%
    bind_cols(transactions_table)
  
  # Add senator_assets_table to master dataframe
  senator_transactions_all <- senator_transactions_all %>%
    bind_rows(senator_transactions_table)
  
  ####
  # Grab liabilities table
  ####
  liabilities_table <- tibble(
    data = financial_tables
  ) %>%
  filter(str_detect(data,"Incurred")) %>%
  unnest() %>%
  clean_names() %>%
  mutate(across(everything(), as.character))
  
  # Bind asset table back to senator table
  senator_liabilities_table <- senator_table %>%
    bind_cols(liabilities_table)
  
  # Add senator_assets_table to master dataframe
  senator_liabilities_all <- senator_liabilities_all %>%
    bind_rows(senator_liabilities_table)
  
  #####
  # Grab positions table
  ####
  positions_table <- tibble(
    data = financial_tables
  ) %>%
  filter(str_detect(data,"Position Dates")) %>%
  unnest() %>%
  clean_names() %>%
  mutate(across(everything(), as.character))
  
  # Bind asset table back to senator table
  senator_positions_table <- senator_table %>%
    bind_cols(positions_table)
  
  # Add senator_assets_table to master dataframe
  senator_positions_all <- senator_positions_all %>%
    bind_rows(senator_positions_table)
  
  #####
  # Grab earned income table
  ####
  earned_income_table <- tibble(
    data = financial_tables
  ) %>%
  filter(str_detect(data,"Who Was Paid")) %>%
  unnest() %>%
  clean_names() %>%
  mutate(across(everything(), as.character))
  
  # Bind asset table back to senator table
  senator_earned_income_table <- senator_table %>%
    bind_cols(earned_income_table)
  
  # Add senator_assets_table to master dataframe
  senator_earned_income_all <- senator_earned_income_all %>%
    bind_rows(senator_earned_income_table)
  
  #####
  # Grab agreements table
  ####
  agreements_table <- tibble(
    data = financial_tables
  ) %>%
  filter(str_detect(data,"Status and Terms")) %>%
  unnest() %>%
  clean_names() %>%
  mutate(across(everything(), as.character))
  
  # Bind asset table back to senator table
  senator_agreements_table <- senator_table %>%
    bind_cols(agreements_table)
  
  # Add senator_assets_table to master dataframe
  senator_agreements_all <- senator_agreements_all %>%
    bind_rows(senator_agreements_table)
  
  
  

}

write_rds(senators_all,"data/senators_all.rds")
write_rds(senator_assets_all,"data/senate_assets.rds")
write_rds(senator_transactions_all,"data/senate_transactions.rds")
write_rds(senator_liabilities_all,"data/senate_liabilities.rds")
write_rds(senator_positions_all,"data/senate_positions.rds")
write_rds(senator_earned_income_all,"data/senate_earned_income.rds")
write_rds(senator_agreements_all,"data/senate_agreements.rds")

rm(list=ls()[! ls() %in% c("senators_all","senator_assets_all","senator_transactions_all","senator_liabilities_all","senator_positions_all","senator_earned_income_all","senator_agreements_all")])


```
